apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: 
  name: authelia
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./authelia
  prune: false
  suspend: true
  force: false
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
