apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitlab
  prune: false
  force: false
  suspend: true
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
