apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: 
  name: actions-runner-controller
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./actions-runner-controller
  prune: false
  suspend: false
  force: false
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
