apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vikunja
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./vikunja-ton
  prune: false
  suspend: false
  force: false
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
