apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-conf
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./istio-system-conf
  prune: false
  force: false
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
