apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rustfs-operator-conf
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./rustfs-operator-conf-ton
  prune: false
  force: false
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
