# Haven't got this to work due this error, just jumping to rustfs instead
#
# 500 Internal Server Error
# Code: InternalError
# Message: Internal error: Layout not ready.

# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: garage
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   path: ./garage-ton
#   prune: false
#   suspend: false
#   force: false
#   sourceRef:
#     kind: GitRepository
#     name: lag0-fleet-manifests-git
