apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden-kubernetes-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./vaultwarden-kubernetes-secrets-ton
  prune: false
  force: false
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
